### ISSUE TITLE
Serve site with SSL

### ISSUE THREAD

**Issue by elmatou** [Arcath/jekyll-atom#80]
Nice work and thank you to bring this to us.

One feature which would be very convenient for me is to be able to start the built in jekyll server with ssl keys and certificate.

More and more of advanced browser API requires SSL to work (eg : workers, MediaAPI, ...) and more are coming.
https://www.digicert.com/blog/https-only-features-in-browsers/

the right command for jekyll is `jekyll serve --ssl-key key.pem --ssl-cert cert.pem`
key and cert files could be added to `_config.yml` easily
```yml
atom:
  serveCommand:
    - jekyll
    - serve
    - --ssl-key key.pem
    - --ssl-cert cert.pem
```

Tell me if this feature could be useful for anybody
